name: adtrace_sdk
description: This is the Flutter SDK of AdTrace. You can read more about AdTrace at adtrace.io
homepage: https://github.com/adtrace/adtrace_sdk_flutter
version: 1.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ">=1.1.6 <2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: io.adtrace.sdk.flutter
        pluginClass: AdTraceSdk
      ios:
        pluginClass: AdtracetSdk
